config/routes.rb
Tmanagement::Application.routes.draw do
  resources :priority_labels
  resources :tasks do
    collection do
      post 'update_tasks_position', :to => 'tasks#update_tasks_position', :as => 'update_tasks_position'
    end
  end
  resources :lists
  resources :boards
  resources :dashboard, :only => [:index]

   root :to => 'dashboard#index'

end

app/models/priority_label.rb
class PriorityLabel < ActiveRecord::Base
  attr_accessible :color, :title
  has_many :tasks
end

app/controllers/priority_labels_controller.rb
class PriorityLabelsController < ApplicationController
  # GET /priority_labels
  # GET /priority_labels.json
  def index
    @priority_labels = PriorityLabel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @priority_labels }
    end
  end

  # GET /priority_labels/1
  # GET /priority_labels/1.json
  def show
    @priority_label = PriorityLabel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @priority_label }
    end
  end

  # GET /priority_labels/new
  # GET /priority_labels/new.json
  def new
    @priority_label = PriorityLabel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @priority_label }
    end
  end

  # GET /priority_labels/1/edit
  def edit
    @priority_label = PriorityLabel.find(params[:id])
  end

  # POST /priority_labels
  # POST /priority_labels.json
  def create
    @priority_label = PriorityLabel.new(params[:priority_label])

    respond_to do |format|
      if @priority_label.save
        format.html { redirect_to @priority_label, notice: 'label was successfully created.' }
        format.json { render json: @priority_label, status: :created, location: @priority_label }
      else
        format.html { render action: "new" }
        format.json { render json: @priority_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /priority_labels/1
  # PUT /priority_labels/1.json
  def update
    @priority_label = PriorityLabel.find(params[:id])

    respond_to do |format|
      if @priority_label.update_attributes(params[:priority_label])
        format.html { redirect_to @priority_label, notice: 'Priority label was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @priority_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /priority_labels/1
  # DELETE /priority_labels/1.json
  def destroy
    @priority_label = PriorityLabel.find(params[:id])
    @priority_label.destroy

    respond_to do |format|
      format.html { redirect_to priority_labels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/priority_labels_helper.rb
module PriorityLabelsHelper
end

app/views/priority_labels/_form.html.erb
<%= form_for(@priority_label) do |f| %>
  <% if @priority_label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@priority_label.errors.count, "error") %> prohibited this priority_label from being saved:</h2>

      <ul>
      <% @priority_label.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/priority_labels/edit.html.erb
<h1>Editing priority_label</h1>

<%= render 'form' %>

<%= link_to 'Show', @priority_label %> |
<%= link_to 'Back', priority_labels_path %>

app/views/priority_labels/index.html.erb
<h1>Listing priority_labels</h1>

<table>
  <tr>
    <th>Color</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @priority_labels.each do |priority_label| %>
  <tr>
    <td><%= priority_label.color %></td>
    <td><%= priority_label.title %></td>
    <td><%= link_to 'Show', priority_label %></td>
    <td><%= link_to 'Edit', edit_priority_label_path(priority_label) %></td>
    <td><%= link_to 'Destroy', priority_label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Priority label', new_priority_label_path %>

app/views/priority_labels/new.html.erb
<h1>New priority_label</h1>

<%= render 'form' %>

<%= link_to 'Back', priority_labels_path %>

app/views/priority_labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Color:</b>
  <%= @priority_label.color %>
</p>

<p>
  <b>Title:</b>
  <%= @priority_label.title %>
</p>


<%= link_to 'Edit', edit_priority_label_path(@priority_label) %> |
<%= link_to 'Back', priority_labels_path %>